### ISSUE TITLE
`Cannot find module 'vite-plugin-glsl'` after upgrading to v2                                                                              `

### ISSUE THREAD

**Issue by stefanobartoletti** [Tresjs/nuxt#69]
### Describe the bug

Pretty much self explanatory, after upgrading to v2, I get this error `Cannot find module 'vite-plugin-glsl'` 

I had a look in the source code, and looks like the problem originates here

https://github.com/Tresjs/nuxt/blob/4039d2578267fb04295d94ad3c816895df98721b/src/module.ts#L8

basically the package is imported but in `package.json` is only included in `devDependencies`, so not installed when installing the module.

Moving it to `dependencies` should fix this.

### Reproduction

---

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
